# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6c149db4f26daefcf5faf290797af05897318c80a4b50ffd674a6c3ee4aba634836b9ae1a4f75aa3cd62afe4c6d6e8f788d6a436a2421bb841eeda84391d3e4

test:
  secret_key_base: dacc13e99a05debf93f00937c83c0fe3d56ad899a63420bc7c685ac8756074e668187ec972830c89ad1b5a2759288f302062b0801b95a52f69cfb58fdcd7f479

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
